import Head from "next/head";
const HeadContent = () => {
  return (
    <Head>
      <title>Awesome</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}

export default HeadContent;
